# Generated by Django 6.0.6 on 2026-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='event/')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('SELESAI', 'Selesai')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
