# Generated by Django 6.0.6 on 2026-07-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tiket', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('REGULER', 'Reguler'), ('VIP', 'VIP')], default='REGULER', max_length=20)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
        ),
    ]
