# Generated by Django 6.0.6 on 2026-07-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(choices=[('TRANSFER', 'Transfer Bank'), ('EWALLET', 'E-Wallet'), ('QRIS', 'QRIS')], max_length=20)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='payment/')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('SUCCESS', 'Berhasil'), ('FAILED', 'Ditolak')], default='PENDING', max_length=20)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.booking')),
            ],
        ),
    ]
