# Generated by Django 6.0.6 on 2026-07-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tiket', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('USED', 'Sudah Digunakan'), ('EXPIRED', 'Kadaluarsa')], default='VALID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.booking')),
            ],
        ),
    ]
